name: Docker
on: [workflow_dispatch, push]

jobs:
    docker-jobs:
        runs-on: self-hosted
        container:
            image: node:24-alpine3.21
            env:
                API_URL: some.com
            ports:
                - 80
        steps:
            - name: Log Node & OS Versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log Env
              run: |
                echo $API_URL
